# Generated by Django 5.0.7 on 2024-07-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='add_time',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Untitled Book', max_length=255),
        ),
    ]
